# Generated by Django 4.1.1 on 2022-10-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('text', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопрос',
            },
        ),
    ]
