# Generated by Django 4.1.1 on 2022-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonuses_gifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Бонусы и подарки')),
            ],
            options={
                'verbose_name': 'Бонусы и подарки',
                'verbose_name_plural': 'Бонус и подарок',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Доставки',
                'verbose_name_plural': 'Доставка',
            },
        ),
        migrations.CreateModel(
            name='Guarantees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Гарантии')),
            ],
            options={
                'verbose_name': 'Гарантии',
                'verbose_name_plural': 'Гарантия',
            },
        ),
        migrations.CreateModel(
            name='How_to_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Как заказать')),
            ],
            options={
                'verbose_name': 'Как заказать',
                'verbose_name_plural': 'Как заказать',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание на главное странице')),
            ],
            options={
                'verbose_name': 'Описание на главное странице',
                'verbose_name_plural': 'Описание на главное странице',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Оплата')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
    ]
