# Generated by Django 4.1.1 on 2022-10-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Контен')),
            ],
            options={
                'verbose_name': 'Акции',
                'verbose_name_plural': 'Акция',
            },
        ),
    ]
