# Generated by Django 4.1.1 on 2022-10-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_privacy_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='О компании')),
            ],
            options={
                'verbose_name': 'Возрастное ограничение',
                'verbose_name_plural': 'Возрастное ограничение',
            },
        ),
    ]
