# Generated by Django 4.1.1 on 2022-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_age_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Контакты')),
                ('time', models.CharField(blank=True, max_length=250, verbose_name='Режим работы')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Номер')),
                ('mail', models.CharField(blank=True, max_length=250, verbose_name='Почта')),
                ('vk', models.URLField(blank=True, max_length=250, verbose_name='Ссылка на VK')),
                ('telegram', models.URLField(blank=True, max_length=250, verbose_name='Ссылка на Telegram')),
                ('whatsapp', models.URLField(blank=True, max_length=250, verbose_name='Ссылка на WhatsApp')),
            ],
            options={
                'verbose_name': 'Контакты и режимы работы',
                'verbose_name_plural': 'Контакт и режим работы',
            },
        ),
    ]
